version: "3.3"
services:
  db:
    image: mysql
    network_mode: bridge
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root